[package]
name = "light-cli"
version = "0.1.0"
authors = ["Rudi Horn <dyn-git@rudi-horn.de>"]

[dependencies]
nb = "0.1.1"
embedded-hal = "0.1.2"
heapless = "0.3.6"

[dev-dependencies]
cortex-m = "0.5.0"
stm32f103xx-hal = { git = "https://github.com/japaric/stm32f103xx-hal" }
panic-abort = "0.1.1"
